
TARGET_META_ARCH=armv4

TARGET_ARCH=arm
TARGET_FULL_ARCH=$TARGET_ARCH-v4-linux-uclibcgnueabi
TARGET_KERNEL_NAME=uImage
TARGET_LIBC_CFLAGS="-g -O2 -march=armv4t -mtune=arm920t -fPIC"
TARGET_CFLAGS="$TARGET_LIBC_CFLAGS -fPIC"

